import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { expect, test } from '@playwright/test'

test('field MP4 integrity, switching, seek, loop and CTA timing', async ({ page, request }) => {
  test.setTimeout(180000)
  const directory = resolve('../assets/incoming')
  const files = [process.env.CTA_TEST_VIDEO_A, process.env.CTA_TEST_VIDEO_B].filter((name): name is string => !!name && existsSync(resolve(directory, name)))
  test.skip(files.length < 2, 'Set CTA_TEST_VIDEO_A and CTA_TEST_VIDEO_B to two local MP4 paths; binaries are never committed.')
  const events: string[] = []
  page.on('console', (message) => { if (message.text().includes('[CTA video]')) events.push(message.text()) })
  await page.goto('/')
  await page.getByLabel('Media Type').selectOption('video')
  const video = page.locator('video')
  const overlay = page.locator('.canvas-media-overlay')
  let previous = ''
  for (const name of [...files, files[0]]) {
    const bytes = readFileSync(resolve(directory, name))
    await page.getByLabel('Choose Video').setInputFiles({ name, mimeType: 'video/mp4', buffer: bytes })
    await expect(page.getByRole('status').filter({ hasText: 'Uploaded' })).toBeVisible()
    await expect(video).not.toHaveAttribute('src', previous)
    const src = (await video.getAttribute('src'))!
    previous = src
    const response = await request.get(src)
    expect(response.status()).toBe(200)
    expect(response.headers()['content-type']).toBe('video/mp4')
    expect(Number(response.headers()['content-length'])).toBe(bytes.length)
    expect((await response.body()).equals(bytes)).toBe(true)
    const range = await request.get(src, { headers: { Range: 'bytes=0-15' } })
    expect(range.status()).toBe(206)
    expect(range.headers()['content-range']).toBe(`bytes 0-15/${bytes.length}`)
    const tail = await request.get(src, { headers: { Range: 'bytes=-16' } })
    expect(tail.status()).toBe(206)
    expect((await tail.body()).equals(bytes.subarray(-16))).toBe(true)
    await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.currentTime), { timeout: 15000 }).toBeGreaterThan(0)
    expect(await video.evaluate((v: HTMLVideoElement) => v.currentSrc)).toBe(src)
    expect(await video.evaluate((v: HTMLVideoElement) => v.videoWidth)).toBeGreaterThan(0)
    await video.evaluate((v: HTMLVideoElement) => { v.pause(); v.currentTime = 0 })
    await expect(overlay).toHaveCount(0)
    await video.evaluate((v: HTMLVideoElement) => { v.currentTime = v.duration - 2 })
    await expect(overlay).toBeVisible()
    await video.evaluate((v: HTMLVideoElement) => { v.currentTime = 0 })
    await expect(overlay).toHaveCount(0)
    await page.getByLabel('CTA Display').selectOption('always')
    await expect(overlay).toBeVisible()
    await page.getByLabel('CTA Display').selectOption('hidden')
    await expect(overlay).toHaveCount(0)
    await page.getByLabel('CTA Display').selectOption('last-seconds')
  }
  await page.getByLabel('CTA seconds').fill('5')
  await video.evaluate((v: HTMLVideoElement) => { v.currentTime = v.duration - 4 })
  await expect(overlay).toBeVisible()
  await page.getByLabel('CTA seconds').fill('3')
  await expect(overlay).toHaveCount(0)
  await video.evaluate(async (v: HTMLVideoElement) => { v.currentTime = v.duration - 0.4; await v.play() })
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.currentTime)).toBeLessThan(2)
  await expect(overlay).toHaveCount(0)
  await page.waitForFunction((src) => Object.values(localStorage).some((v) => v.includes(src)), previous)
  await page.reload()
  await expect(video).toHaveAttribute('src', previous)
  await expect(page.getByLabel('CTA Display')).toHaveValue('last-seconds')
  await expect.poll(() => video.evaluate((v: HTMLVideoElement) => v.currentTime)).toBeGreaterThan(0)
  await test.info().attach('video-events', { body: events.join('\n'), contentType: 'text/plain' })
})

test('playback failure exposes code and currentSrc', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Media Type').selectOption('video')
  await page.route('**/api/media/upload', (route) => route.fulfill({ json: { filename: 'missing.mp4', url: 'http://127.0.0.1:8100/media/missing.mp4' } }))
  await page.getByLabel('Choose Video').setInputFiles({ name: 'missing.mp4', mimeType: 'video/mp4', buffer: Buffer.from('bad') })
  await expect(page.getByRole('alert')).toContainText('Video playback failed')
  await page.getByText('Playback diagnostics').click()
  await expect(page.getByRole('alert')).toContainText('"code":4')
  await expect(page.getByRole('alert')).toContainText('/media/missing.mp4')
  await page.getByLabel('Media Type').selectOption('image')
  await expect(page.getByRole('alert')).toHaveCount(0)
})


test('AI CTA apply preserves video display settings', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Media Type').selectOption('video')
  await page.getByLabel('CTA Display').selectOption('hidden')
  await page.route('**/api/ai/generate-cta', (route) => route.fulfill({ json: { headline: 'AI headline', message: 'AI message', buttonText: 'AI action', subText: 'AI subtitle' } }))
  await page.getByRole('button', { name: 'Generate CTA', exact: true }).click()
  await page.getByRole('button', { name: 'Apply', exact: true }).click()
  await expect(page.getByLabel('Headline', { exact: true })).toHaveValue('AI headline')
  await expect(page.getByLabel('Action 1', { exact: true })).toHaveValue('AI action')
  await expect(page.getByLabel('CTA Display')).toHaveValue('hidden')
})
